from .smsa2_region_helper import *

WORLD7: Smsa2Region = Smsa2Region(
    Smsa2RegionName.WORLD7,
    ticketed = "World 7 Ticket",
    shines = [
        Shine("7-1 Shine", in_game_bit = 8,
            standard = Requirements([[NozzleType.hover], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [SPRAY_AND_TURBO], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.turbo], [SPRAY_AND_ROCKET], [NozzleType.bubble]])),
        Shine("7-2 Shine", in_game_bit = 9,
            standard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("7-3 Shine", in_game_bit = 18,
            standard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("7-4 Shine", in_game_bit = 19,
            standard = Requirements([[SPRAY_AND_ROCKET], [HOVER_AND_ROCKET]]),
            hard = Requirements([[SPRAY_AND_ROCKET], [HOVER_AND_ROCKET], [TURBO_AND_ROCKET], [NozzleType.bubble]]),
            expert = Requirements([[SPRAY_AND_ROCKET], [HOVER_AND_ROCKET], [TURBO_AND_ROCKET], [NozzleType.bubble]])),
        Shine("7-5 Shine", in_game_bit = 28,
            standard = Requirements([[NozzleType.hover], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("7-6 Shine", in_game_bit = 29),
        Shine("7-7 Shine", in_game_bit = 38),
        Shine("7-8 Shine", in_game_bit = 39)
    ],
    blue_coins = [
        BlueCoin("7-1", in_game_bit = 379,
            standard = Requirements([[NozzleType.hover]]),
            hard = Requirements([[NozzleType.hover], [SPRAY_AND_TURBO], [SPRAY_AND_ROCKET], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [SPRAY_AND_TURBO], [NozzleType.bubble]])),
        BlueCoin("7-2", in_game_bit = 380),
        BlueCoin("7-3", in_game_bit = 381),
        BlueCoin("7-4", in_game_bit = 382,
            standard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]])),
        BlueCoin("7-5", in_game_bit = 383,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        BlueCoin("7-6", in_game_bit = 384,
            standard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]])),
        BlueCoin("7-7", in_game_bit = 385),
        BlueCoin("7-8", in_game_bit = 386),
    ],
    parent_region = "Menu"
)