from .smsa2_region_helper import *

WORLD3: Smsa2Region = Smsa2Region(
    Smsa2RegionName.WORLD3,
    ticketed = "World 3 Ticket",
    shines = [
        Shine("3-1 Shine", in_game_bit = 10,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("3-2 Shine", in_game_bit = 11,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("3-3 Shine", in_game_bit = 12),
        Shine("3-4 Shine", in_game_bit = 13,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("3-5 Shine", in_game_bit = 14,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("3-6 Shine", in_game_bit = 15,
            standard = Requirements([[NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.rocket], [NozzleType.bubble]])),
        Shine("3-7 Shine", in_game_bit = 16,
            standard = Requirements([[NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("3-8 Shine", in_game_bit = 17,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]))
    ],
    blue_coins = [
        BlueCoin("3-1", in_game_bit = 221,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]])),
        BlueCoin("3-2", in_game_bit = 222,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        BlueCoin("3-3", in_game_bit = 223),
        BlueCoin("3-4", in_game_bit = 224,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        BlueCoin("3-5", in_game_bit = 225,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        BlueCoin("3-6", in_game_bit = 226),
        BlueCoin("3-7", in_game_bit = 227),
        BlueCoin("3-8", in_game_bit = 228,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]])),
    ],
    parent_region = "Menu"
)