from .smsa2_region_helper import *

WORLD11: Smsa2Region = Smsa2Region(
    Smsa2RegionName.WORLD11,
    ticketed = "World 11 Ticket",
    shines = [
        Shine("11-1 Shine", in_game_bit = 96,
            standard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("11-2 Shine", in_game_bit = 97,
            standard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("11-3 Shine", in_game_bit = 98,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("11-4 Shine", in_game_bit = 99,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("11-5 Shine", in_game_bit = 100),
        Shine("11-6 Shine", in_game_bit = 101,
            standard = Requirements([[NozzleType.hover], [NozzleType.bubble]])),
        Shine("11-7 Shine", in_game_bit = 102,
            standard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("11-8 Shine", in_game_bit = 103,
            standard = Requirements([[NozzleType.hover]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]]))
    ],
    blue_coins = [
        BlueCoin("11-1", in_game_bit = 129,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        BlueCoin("11-2", in_game_bit = 130),
        BlueCoin("11-3", in_game_bit = 131,
            standard = Requirements([[NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.rocket], [TURBO_AND_HOVER], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.rocket], [TURBO_AND_HOVER], [NozzleType.bubble]])),
        BlueCoin("11-4", in_game_bit = 132,
            standard = Requirements([[NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.rocket], [SPRAY_AND_TURBO], [NozzleType.bubble]])),
        BlueCoin("11-5", in_game_bit = 133),
        BlueCoin("11-6", in_game_bit = 134),
        BlueCoin("11-7", in_game_bit = 135),
        BlueCoin("11-8", in_game_bit = 136,
            standard = Requirements([[NozzleType.hover]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
    ],
    parent_region = "Menu"
    )