from .smsa2_region_helper import *

WORLD6: Smsa2Region = Smsa2Region(
    Smsa2RegionName.WORLD6,
    ticketed = "World 6 Ticket",
    shines = [
        Shine("6-1 Shine", in_game_bit = 40,
            standard = Requirements([[NozzleType.hover]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("6-2 Shine", in_game_bit = 41,
            standard = Requirements([[NozzleType.hover]]),
            hard = Requirements([[NozzleType.spray], [NozzleType.hover]]),
            expert = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("6-3 Shine", in_game_bit = 42),
        Shine("6-4 Shine", in_game_bit = 43),
        Shine("6-5 Shine", in_game_bit = 44,
            standard = Requirements([[NozzleType.hover], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("6-6 Shine", in_game_bit = 45,
            standard = Requirements([[NozzleType.hover], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.bubble]])),
        Shine("6-7 Shine", in_game_bit = 46),
        Shine("6-8 Shine", in_game_bit = 47,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]))
    ],
    blue_coins = [
        BlueCoin("6-1", in_game_bit = 371,
            standard = Requirements([[NozzleType.hover]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        BlueCoin("6-2", in_game_bit = 372,
            standard = Requirements([[NozzleType.hover], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        BlueCoin("6-3", in_game_bit = 373),
        BlueCoin("6-4", in_game_bit = 374),
        BlueCoin("6-5", in_game_bit = 375),
        BlueCoin("6-6", in_game_bit = 376,
            standard = Requirements([[NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.spray], [NozzleType.hover], [NozzleType.turbo], [NozzleType.bubble]])),
        BlueCoin("6-7", in_game_bit = 377),
        BlueCoin("6-8", in_game_bit = 378),
    ],
    parent_region = "Menu"
)