from .smsa2_region_helper import *

WORLD4: Smsa2Region = Smsa2Region(
    Smsa2RegionName.WORLD4,
    ticketed = "World 4 Ticket",
    shines = [
        Shine("4-1 Shine", in_game_bit = 20,
            standard = Requirements([[NozzleType.turbo]]),
            hard = Requirements([[NozzleType.turbo]]),
            expert = Requirements([[NozzleType.turbo]])),
        Shine("4-2 Shine", in_game_bit = 21),
        Shine("4-3 Shine", in_game_bit = 22),
        Shine("4-4 Shine", in_game_bit = 23,
            standard = Requirements([[NozzleType.hover], [SPRAY_AND_ROCKET], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [SPRAY_AND_ROCKET], [TURBO_AND_ROCKET], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]])),
        Shine("4-5 Shine", in_game_bit = 24,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.turbo], [NozzleType.bubble]])),
        Shine("4-6 Shine", in_game_bit = 25),
        Shine("4-7 Shine", in_game_bit = 26,
            standard = Requirements([[NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.rocket], [NozzleType.bubble]])),
        Shine("4-8 Shine", in_game_bit = 27,
            standard = Requirements([[NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.rocket], [NozzleType.hover], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.rocket], [NozzleType.hover], [NozzleType.bubble]]))
    ],
    blue_coins = [
        BlueCoin("4-1", in_game_bit = 271),
        BlueCoin("4-2", in_game_bit = 272),
        BlueCoin("4-3", in_game_bit = 273),
        BlueCoin("4-4", in_game_bit = 274,
            standard = Requirements([[NozzleType.hover], [SPRAY_AND_ROCKET], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [SPRAY_AND_ROCKET], [TURBO_AND_ROCKET], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]])),
        BlueCoin("4-5", in_game_bit = 275,
            standard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.hover], [NozzleType.rocket], [NozzleType.bubble]])),
        BlueCoin("4-6", in_game_bit = 276),
        BlueCoin("4-7", in_game_bit = 277),
        BlueCoin("4-8", in_game_bit = 278,
            standard = Requirements([[NozzleType.rocket], [NozzleType.bubble]]),
            hard = Requirements([[NozzleType.rocket], [NozzleType.hover], [NozzleType.bubble]]),
            expert = Requirements([[NozzleType.rocket], [NozzleType.hover], [NozzleType.bubble]])),
    ],
    parent_region = "Menu"
)